---
languageCode: "en-us"
title: "JointBox - Your DIY smart home. Simplified."
baseURL: "https://jointbox.github.io/docs"
metaDataFormat: "yaml"
# color-codes for highlighting derived from this style
pygmentsStyle: "monokai"
pygmentsCodeFences: true

params:
  GithubLink: "https://github.com/JointBox/jointbox"
  TwitterLink: "https://twitter.com/"
  YoutubeLink: "https://youtube.com/"
  Author: "Dmitry Berezovsky"
...