---
languageCode: "en-us"
title: "JointBox - Your DIY smart home. Simplified."
baseURL: "http://jointbox.org/"
metaDataFormat: "yaml"
# color-codes for highlighting derived from this style
pygmentsStyle: "monokai"
pygmentsCodeFences: true
pygmentsUseClasses: true

sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

params:
  GithubLink: "https://github.com/JointBox/jointbox"
  TwitterLink: "https://twitter.com/"
  YoutubeLink: "https://youtube.com/"
  Author: "Dmitry Berezovsky"
...